# Generated by Django 6.0.1 on 2026-03-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Falesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_roccia', models.CharField(max_length=100)),
                ('latitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('comune', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('regione', models.CharField(max_length=100)),
                ('paese', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('esposizione', models.CharField(max_length=50)),
                ('stagione_consigliata', models.CharField(max_length=50)),
                ('immagine', models.ImageField(blank=True, upload_to='falesie/')),
            ],
        ),
        migrations.CreateModel(
            name='Percorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('grado', models.CharField(max_length=10)),
                ('n_soste', models.IntegerField()),
                ('tipo', models.CharField(choices=[('sport', 'Sportiva'), ('boulder', 'Boulder'), ('trad', 'Tradizionale')], max_length=20)),
                ('altezza', models.IntegerField()),
                ('n_spittature', models.IntegerField()),
                ('distanza_spit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(blank=True, upload_to='percorsi/')),
                ('falesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percorsi', to='falesie.falesia')),
            ],
        ),
    ]
