# Generated by Django 6.0.1 on 2026-03-25 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('falesie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('falesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falesie.falesia')),
                ('percorso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falesie.percorso')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falesie.falesia')),
                ('percorso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falesie.percorso')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('falesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falesie.falesia')),
                ('percorso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falesie.percorso')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
