# Generated by Django 6.0.3 on 2026-03-25 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Falesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_roccia', models.CharField(choices=[('limestone', 'Calcare'), ('granite', 'Granito'), ('sandstone', 'Arenaria'), ('basalt', 'Basalto'), ('conglomerate', 'Conglomerato'), ('schist', 'Scisto'), ('gneiss', 'Gneiss'), ('quartzite', 'Quarzite'), ('dolomite', 'Dolomia'), ('tuff', 'Tufo'), ('rhyolite', 'Riolite'), ('gabbro', 'Gabbro'), ('slate', 'Ardesia'), ('marble', 'Marmo'), ('volcanic', 'Vulcanico')], max_length=100)),
                ('latitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('comune', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('regione', models.CharField(max_length=100)),
                ('paese', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('esposizione', models.CharField(choices=[('nord', 'Nord'), ('nord-est', 'Nord-Est'), ('est', 'Est'), ('sud-est', 'Sud-Est'), ('sud', 'Sud'), ('sud-ovest', 'Sud-Ovest'), ('ovest', 'Ovest'), ('nord-ovest', 'Nord-Ovest')], max_length=50)),
                ('stagione_consigliata', models.CharField(choices=[('primavera', 'Primavera'), ('estate', 'Estate'), ('autunno', 'Autunno'), ('inverno', 'Inverno')], max_length=50)),
                ('immagine', models.ImageField(blank=True, upload_to='falesie/')),
            ],
        ),
        migrations.CreateModel(
            name='Percorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('grado', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4a', '4a'), ('4b', '4b'), ('4c', '4c'), ('5a', '5a'), ('5b', '5b'), ('5c', '5c'), ('6a', '6a'), ('6a+', '6a+'), ('6b', '6b'), ('6b+', '6b+'), ('6c', '6c'), ('6c+', '6c+'), ('7a', '7a'), ('7a+', '7a+'), ('7b', '7b'), ('7b+', '7b+'), ('7c', '7c'), ('7c+', '7c+'), ('8a', '8a'), ('8a+', '8a+'), ('8b', '8b'), ('8b+', '8b+'), ('8c', '8c'), ('8c+', '8c+')], max_length=10)),
                ('n_soste', models.IntegerField()),
                ('tipo', models.CharField(choices=[('sport', 'Sportiva'), ('boulder', 'Boulder'), ('trad', 'Tradizionale')], max_length=20)),
                ('altezza', models.IntegerField()),
                ('n_spittature', models.IntegerField()),
                ('distanza_spit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(blank=True, upload_to='percorsi/')),
                ('falesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percorsi', to='generale.falesia')),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('falesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generale.falesia')),
                ('percorso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generale.percorso')),
            ],
        ),
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generale.falesia')),
                ('percorso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generale.percorso')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('falesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generale.falesia')),
                ('percorso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generale.percorso')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
