# Generated by Django 6.0.1 on 2026-04-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falesia',
            name='paese',
        ),
    ]
