# Generated by Django 6.0.1 on 2026-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generale', '0002_remove_falesia_paese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falesia',
            name='esposizione',
            field=models.CharField(blank=True, choices=[('nord', 'Nord'), ('nord-est', 'Nord-Est'), ('est', 'Est'), ('sud-est', 'Sud-Est'), ('sud', 'Sud'), ('sud-ovest', 'Sud-Ovest'), ('ovest', 'Ovest'), ('nord-ovest', 'Nord-Ovest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='falesia',
            name='latitudine',
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
        migrations.AlterField(
            model_name='falesia',
            name='longitudine',
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
    ]
