# Generated by Django 6.0.1 on 2026-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generale', '0004_alter_falesia_latitudine_alter_falesia_longitudine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falesia',
            name='latitudine',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='falesia',
            name='longitudine',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
    ]
