# Generated by Django 6.0.1 on 2026-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generale', '0005_alter_falesia_latitudine_alter_falesia_longitudine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falesia',
            name='latitudine',
            field=models.DecimalField(decimal_places=12, max_digits=16),
        ),
        migrations.AlterField(
            model_name='falesia',
            name='longitudine',
            field=models.DecimalField(decimal_places=12, max_digits=16),
        ),
    ]
